### ISSUE TITLE
Tag range returns an error

### ISSUE THREAD

**Issue by khan990** [lob/generate-changelog#51]
I am getting an error when requesting a changelog with in the range. But I am getting commits in commandline by executing `git log -E --format=%H%n%s%n%b%n===END=== v2.0.0-alpha.12..v2.0.0-alpha.17`.

```typescript
generateLog.generate(<generateLog.Options>{
            patch: true,
            major: true,
            tag: 'v2.0.0-alpha.12..v2.0.0-alpha.17',
            repoUrl: repositoryUrl
        }).then((changeLog) => {
            console.log(changeLog);
        }).catch((err) => {
            console.error(err);
        });
```

I get the following error:
> **Note**: I printed out error by changing line 44 of git.js `throw new Error('no commits found \n' + err);`

```
Error: no commits found
Error: Command failed: git log -E --format=%H%n%s%n%b%n===END=== v2.0.0-alpha.12..v2.0.0-alpha.17
fatal: ambiguous argument 'v2.0.0-alpha.12..v2.0.0-alpha.17': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at M:\change-log\node_modules\generate-changelog\lib\git.js:44:11
    at tryCatcher (M:\change-log\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (M:\change-log\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (M:\change-log\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (M:\change-log\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (M:\change-log\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (M:\change-log\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (M:\change-log\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (M:\change-log\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (M:\change-log\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by khan990** [comment]
I noticed my mistake, I had to be in the working directory of git repository for it to work.
